/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface KickPatternFamily {
  id: number;
  name: string;
  category: 'Bay' | 'Detroit' | 'Off-Grid' | 'Minimal' | 'Heavy';
  description: string;
  // 8 bars, each bar is a list of steps (0..15) where the kick hits
  // with optional velocity weights (0.7 .. 1.0) and microtiming ticks (-20..+20)
  bars: { step: number; velocity?: number; micro?: number }[][];
}

// 40 distinct West Coast / Detroit / Street Slap kick pocket families
export const KICK_FAMILIES: KickPatternFamily[] = [
  {
    id: 1,
    name: 'Sparse Bay Area',
    category: 'Bay',
    description: 'Minimal downbeat anchor with syncopated 11th & 14th step punch. Room for 808 glide.',
    bars: [
      [{ step: 0 }, { step: 10, velocity: 0.9 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10, velocity: 0.85 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13, velocity: 0.85 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }], // bar 8 space/breath
    ],
  },
  {
    id: 2,
    name: 'Detroit Bounce',
    category: 'Detroit',
    description: 'Fast double-tap, syncopated 7th & 15th step pickup. Distinctive Icewear Vezzo stride.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 15, micro: 4 }],
      [{ step: 2 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 15, micro: 4 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 15, micro: 4 }],
      [{ step: 2 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
    ],
  },
  {
    id: 3,
    name: 'Syncopated Off-Grid',
    category: 'Off-Grid',
    description: 'Sliding hits landing on upbeats (3, 7, 11) dragging against the 16th grid.',
    bars: [
      [{ step: 0 }, { step: 3, micro: -5 }, { step: 8 }, { step: 11, micro: 6 }],
      [{ step: 2 }, { step: 8 }, { step: 11 }],
      [{ step: 0 }, { step: 3, micro: -5 }, { step: 8 }, { step: 11, micro: 6 }],
      [{ step: 0 }, { step: 6 }, { step: 9 }, { step: 14 }],
      [{ step: 0 }, { step: 3, micro: -5 }, { step: 8 }, { step: 11, micro: 6 }],
      [{ step: 2 }, { step: 8 }, { step: 11 }],
      [{ step: 0 }, { step: 3 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 4,
    name: 'Delayed Response',
    category: 'Bay',
    description: 'Downbeat omitted on response bars to let 808 sub swallow the bar before kicking back.',
    bars: [
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 6 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 6 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 6 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 5,
    name: 'Intentional Empty Bar',
    category: 'Minimal',
    description: 'Sudden dropout on bar 4 and bar 8 to highlight vocal bar punches and breath.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [], // intentional empty bar
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 13 }, { step: 15 }],
      [], // intentional empty bar
    ],
  },
  {
    id: 6,
    name: 'Aggressive Pocket',
    category: 'Heavy',
    description: 'Triple knock cluster pushing the backbeat. Mozzy & Philthy Rich hard slap style.',
    bars: [
      [{ step: 0 }, { step: 3 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 3 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 3 }, { step: 6 }, { step: 10 }, { step: 13 }, { step: 15 }],
      [{ step: 0 }, { step: 3 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 3 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
    ],
  },
  {
    id: 7,
    name: 'Laid-Back Houston',
    category: 'Bay',
    description: 'Slow rolling pocket with delayed 2nd hit and deep downbeat weight.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 8,
    name: 'Bar-4 Turnaround Only',
    category: 'Off-Grid',
    description: 'Strict discipline on bars 1-3, erupting in rapid 16th knock rolls exclusively at turnaround.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 8 }, { step: 10 }, { step: 13 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
    ],
  },
  {
    id: 9,
    name: 'Pickup Heavy',
    category: 'Detroit',
    description: 'Staggered pickup notes on steps 13, 14, 15 launching hard into next bar downbeat.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }, { step: 13 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 12 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }, { step: 13 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 10,
    name: 'Repeated Groove Core',
    category: 'Bay',
    description: 'Rock-solid hypnotic pocket locking step 0, 7, 10, 14 into an undeniable West Coast groove.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 11,
    name: 'Double-Tap Downbeat',
    category: 'Heavy',
    description: 'Steps 0 and 1 hit in rapid succession, followed by wide space.',
    bars: [
      [{ step: 0 }, { step: 1, velocity: 0.8 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 1, velocity: 0.8 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 1, velocity: 0.8 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 12,
    name: 'Ghost Knock',
    category: 'Off-Grid',
    description: 'Low-velocity ghost kicks preceding the primary 10th and 14th strikes.',
    bars: [
      [{ step: 0 }, { step: 9, velocity: 0.6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 5, velocity: 0.55 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 9, velocity: 0.6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13, velocity: 0.6 }, { step: 14 }],
      [{ step: 0 }, { step: 9, velocity: 0.6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 5, velocity: 0.55 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 13,
    name: '3rd-Beat Push',
    category: 'Detroit',
    description: 'Heavy accent hitting right on beat 3 (step 8) driving the bounce.',
    bars: [
      [{ step: 0 }, { step: 8 }, { step: 11 }],
      [{ step: 2 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 11 }],
      [{ step: 0 }, { step: 6 }, { step: 8 }, { step: 13 }, { step: 15 }],
      [{ step: 0 }, { step: 8 }, { step: 11 }],
      [{ step: 2 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }],
    ],
  },
  {
    id: 14,
    name: 'Off-Beat Stumble',
    category: 'Off-Grid',
    description: 'Intentionally off-balance rhythmic stumble typical of underground Oakland beats.',
    bars: [
      [{ step: 1, micro: 5 }, { step: 6 }, { step: 11 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 1, micro: 5 }, { step: 6 }, { step: 11 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 1, micro: 5 }, { step: 6 }, { step: 11 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 15,
    name: 'Vezzo Stomp',
    category: 'Detroit',
    description: 'Modeled directly after Icewear Vezzo street singles: punchy, plodding, authoritative.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 13, velocity: 0.85 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 13, velocity: 0.85 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 13, velocity: 0.85 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 16,
    name: 'Lavish Drop',
    category: 'Bay',
    description: 'CML / Lavish D Sacramento slap style with sudden drops leaving wide vocal pockets.',
    bars: [
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }],
    ],
  },
  {
    id: 17,
    name: 'Vallejo Roll',
    category: 'Bay',
    description: 'Classic E-40 / Sick Wid It bouncy syncopation.',
    bars: [
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13 }],
      [{ step: 2 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13 }],
      [{ step: 0 }, { step: 6 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13 }],
      [{ step: 2 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 18,
    name: 'Oakland Low-End',
    category: 'Heavy',
    description: 'Sub-focused pattern providing maximum clearance for sweeping 808 glides.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 19,
    name: 'Sacramento Slap',
    category: 'Bay',
    description: 'Aggressive mid-tempo slap locking into Mozzy raw street rhythm.',
    bars: [
      [{ step: 0 }, { step: 3 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 3 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13 }, { step: 15 }],
      [{ step: 0 }, { step: 3 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 20,
    name: '7-Mile Syncopation',
    category: 'Detroit',
    description: 'Detroit 7-Mile bounce with rapid 15th-to-0 turnarounds.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 2 }, { step: 7 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 2 }, { step: 7 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 21,
    name: 'Gratiot Pocket',
    category: 'Detroit',
    description: 'Heavy stutter kick on the 8th bar with delayed downbeat.',
    bars: [
      [{ step: 0 }, { step: 6 }, { step: 11 }],
      [{ step: 2 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 11 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 11 }],
      [{ step: 2 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
    ],
  },
  {
    id: 22,
    name: 'Westside Roll',
    category: 'Bay',
    description: 'Fluid, syncopated kick movement flowing across the entire bar.',
    bars: [
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 11 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 8 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 11 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 23,
    name: 'Eastside Choke',
    category: 'Minimal',
    description: 'Sudden choke on step 10 without turnaround tail.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }],
    ],
  },
  {
    id: 24,
    name: 'Heavy Stride',
    category: 'Heavy',
    description: 'Authoritative double kick accents with deliberate pauses.',
    bars: [
      [{ step: 0 }, { step: 3 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 3 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 3 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 3 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 25,
    name: 'Bar 2-4 Stutter',
    category: 'Detroit',
    description: 'Alternates between straight bar 1 and stuttering responses on bars 2 and 4.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 5 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 5 }, { step: 7 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 5 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 26,
    name: 'Minimal Anchor',
    category: 'Minimal',
    description: 'Ultra-sparse: 2 kicks per bar maximum, allowing massive vocal domination.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }],
    ],
  },
  {
    id: 27,
    name: 'Triple Step Kick',
    category: 'Heavy',
    description: '3 quick successive punches on steps 0, 2, 4 in selected bars.',
    bars: [
      [{ step: 0 }, { step: 2 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 2 }, { step: 10 }],
      [{ step: 0 }, { step: 2 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 2 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 2 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 28,
    name: 'Late 16th Hitch',
    category: 'Off-Grid',
    description: 'Hits pushed back by 10-15 ticks for that human, unquantized street swing.',
    bars: [
      [{ step: 0 }, { step: 7, micro: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 6, micro: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 7, micro: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13, micro: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 7, micro: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 6, micro: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 29,
    name: 'Breath Before Clap',
    category: 'Minimal',
    description: 'Silence directly on steps 3 and 11, giving the snare/clap maximum crack.',
    bars: [
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 30,
    name: 'Drop on Beat 3',
    category: 'Bay',
    description: 'Accents step 8 with secondary kick, keeping steps 4 and 12 completely isolated.',
    bars: [
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }],
    ],
  },
  {
    id: 31,
    name: 'Half-Time Anchor',
    category: 'Minimal',
    description: 'Deliberate downbeat stride with single response per measure.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }],
    ],
  },
  {
    id: 32,
    name: 'Push-and-Pull',
    category: 'Off-Grid',
    description: 'Alternates between early push on bar 1/3 and lazy late pull on bar 2/4.',
    bars: [
      [{ step: 0 }, { step: 6, micro: -8 }, { step: 10, micro: -8 }],
      [{ step: 0 }, { step: 7, micro: 10 }, { step: 11, micro: 10 }],
      [{ step: 0 }, { step: 6, micro: -8 }, { step: 10, micro: -8 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6, micro: -8 }, { step: 10, micro: -8 }],
      [{ step: 0 }, { step: 7, micro: 10 }, { step: 11, micro: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 33,
    name: 'Mobb Kick Slide',
    category: 'Bay',
    description: 'Iconic Bay Area Mobb music rhythm matching Philthy Rich Oakland bounce.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 8 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 34,
    name: 'Cold Winter Detroit',
    category: 'Detroit',
    description: 'Sparse, icy, syncopated kick placing tension on the 11th step.',
    bars: [
      [{ step: 0 }, { step: 11 }],
      [{ step: 2 }, { step: 7 }, { step: 11 }],
      [{ step: 0 }, { step: 11 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 11 }],
      [{ step: 2 }, { step: 7 }, { step: 11 }],
      [{ step: 0 }, { step: 8 }, { step: 11 }],
      [{ step: 0 }],
    ],
  },
  {
    id: 35,
    name: '8-Bar Wave',
    category: 'Heavy',
    description: 'Builds kick density bar by bar until peaking at Bar 4 and Bar 7.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 3 }, { step: 6 }, { step: 10 }, { step: 13 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 36,
    name: 'Turnaround Cluster',
    category: 'Off-Grid',
    description: 'Restrained through bars 1-3, exploding in triplet-feel kick clusters at turnaround.',
    bars: [
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 9 }, { step: 12 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 37,
    name: 'Sub Stomp Sparse',
    category: 'Minimal',
    description: 'Heavy single downbeat followed by a single late punch. Maximum spaciousness.',
    bars: [
      [{ step: 0 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
      [{ step: 0 }, { step: 14 }],
      [{ step: 0 }],
    ],
  },
  {
    id: 38,
    name: 'Delayed Downbeat',
    category: 'Detroit',
    description: 'Hits step 1 instead of step 0 on bars 2 and 6, creating an unexpected head-nod jerk.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 1 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }],
      [{ step: 1 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 39,
    name: 'Double Pickup End',
    category: 'Bay',
    description: 'Sticks double kick pickups into bar endings to whip the listener back around.',
    bars: [
      [{ step: 0 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 8 }, { step: 10 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 40,
    name: 'Full Mobb Drive',
    category: 'Heavy',
    description: 'Relentless West Coast street drive with syncopated 16th kicks and locked groove.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 5 }, { step: 8 }, { step: 11 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 8 }, { step: 10 }, { step: 13 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 5 }, { step: 8 }, { step: 11 }, { step: 14 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 41,
    name: "Cardo 'Got Wings' Swing",
    category: 'Bay',
    description: 'Laid-back West Coast swing bounce as taught in TRIFREEZE masterclass: sparse downbeat, delayed step 10, ghost step 14.',
    bars: [
      [{ step: 0 }, { step: 10 }, { step: 14, velocity: 0.85 }],
      [{ step: 0 }, { step: 6 }, { step: 10, velocity: 0.9 }],
      [{ step: 0 }, { step: 10 }, { step: 14, velocity: 0.85 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14, velocity: 0.8 }, { step: 15 }],
      [{ step: 0 }, { step: 10 }, { step: 14, velocity: 0.85 }],
      [{ step: 0 }, { step: 6 }, { step: 10, velocity: 0.9 }],
      [{ step: 0 }, { step: 8 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 42,
    name: 'Southside 808 Mafia Stomp',
    category: 'Heavy',
    description: 'Aggressive hard-clipping kick directly on top of the 808 attack for instant chest thump: steps 0, 7, 10, 14 with turnaround stutters.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 5 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 13 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 5 }, { step: 10 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 10 }],
    ],
  },
  {
    id: 43,
    name: 'Wheezy Pocket Subtraction',
    category: 'Off-Grid',
    description: 'Airy bounce modeled after Wheezy Outta Here: syncopated offbeats (steps 0, 7, 11) leaving room for 808 decay and vocal flow.',
    bars: [
      [{ step: 0 }, { step: 7, micro: 3 }, { step: 11, micro: -4 }],
      [{ step: 3, micro: -2 }, { step: 8 }, { step: 11 }],
      [{ step: 0 }, { step: 7, micro: 3 }, { step: 11, micro: -4 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 7, micro: 3 }, { step: 11, micro: -4 }],
      [{ step: 3, micro: -2 }, { step: 8 }, { step: 11 }],
      [{ step: 0 }, { step: 7 }, { step: 11 }],
      [{ step: 0 }, { step: 8 }],
    ],
  },
  {
    id: 44,
    name: 'Icewear Vezzo Detroit Slap',
    category: 'Detroit',
    description: 'Signature Detroit Michigan slap stride from Pede tutorial: punchy 0, 7, 10 double-tap with 14-15 turnaround pickup.',
    bars: [
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 15, micro: 4 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 15, micro: 4 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }, { step: 14 }, { step: 15 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 15, micro: 4 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
      [{ step: 0 }, { step: 7 }, { step: 10 }, { step: 14 }],
      [{ step: 0 }, { step: 6 }, { step: 10 }],
    ],
  },
];
